cc_library(
  name = "processor",
  srcs = ["processor.cc"],
  hdrs = [
    "cache_type.h",
    "error_code.h",
    "processor.h",
  ],
  deps = ["//src/command"],
  visibility = ["//src:__subpackages__"],
)
