#ifndef COM_GITHUB_PITEX_PMC_INTERPRETER_PROCESSOR_ERROR_CODES_H_
#define COM_GITHUB_PITEX_PMC_INTERPRETER_PROCESSOR_ERROR_CODES_H_

namespace processor {

enum ErrorCode {
  CONTINUE = 1,
  COMPLETED = 0,
  TIME_LIMIT_EXCEEDED = -1,
  NO_COMMAND_TO_RUN = -2,
  UNKNOWN_COMMAND_TYPE = -3,
  UNKNOWN_ADDRESSING_TYPE = -4,
};

}  // namespace processor

#endif  // COM_GITHUB_PITEX_PMC_INTERPRETER_PROCESSOR_ERROR_CODES_H_
